[package]
name = "infer"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "1"
poly = { path = "../poly" }
sources = { path = "../sources" }
parser = { path = "../parser" }
rowan = "0.15"
rustc-hash = "2"
num-bigint = "0.4"
smallvec = "1.13.2"
serde = { version = "1", features = ["derive"] }

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
js-sys = "0.3"

[dev-dependencies]
specialize = { path = "../specialize" }
control-ir = { path = "../control-ir" }
evidence-vm = { path = "../evidence-vm" }
